<?php

use Monolog\App\Helpers\Crsf\Crsf;

/**
 * Retrieves the CSRF token value.
 *
 * This function provides a global helper to access the CSRF token generated by the `Crsf` class.
 * It can be used to embed the token into forms or for validation purposes.
 *
 * @return string The CSRF token.
 */
function csrf_token(): string
{
    // Instantiate the Crsf class to get the token
    $csrf = new Crsf();

    // Return the generated CSRF token
    return $csrf->getToken();
}